spring:
  main:
    allow-circular-references: true
  application:
    name: machine-manager

file:
  zuper:
    path: ".dev/zuper_registers.xlsx"
  machine:
    path: ".dev/machine_registers.xlsx"

server:
  port: 8080